module.exports = {
  "categories": [
    {
      "name": "Food",
      "pairs": [
        // Original Food pairs
        { "villagerWord": "Pizza", "spyWord": "Calzone" },
        { "villagerWord": "Burger", "spyWord": "Sandwich" },
        { "villagerWord": "Pasta", "spyWord": "Noodles" },
        { "villagerWord": "Rice", "spyWord": "Quinoa" },
        { "villagerWord": "Bread", "spyWord": "Baguette" },
        { "villagerWord": "Cheese", "spyWord": "Butter" },
        { "villagerWord": "Ice Cream", "spyWord": "Gelato" },
        { "villagerWord": "Chocolate", "spyWord": "Fudge" },
        { "villagerWord": "Coffee", "spyWord": "Tea" },
        { "villagerWord": "Soup", "spyWord": "Stew" },
        { "villagerWord": "Salad", "spyWord": "Coleslaw" },
        { "villagerWord": "Steak", "spyWord": "Pork Chop" },
        { "villagerWord": "Sushi", "spyWord": "Sashimi" },
        { "villagerWord": "Taco", "spyWord": "Burrito" },
        { "villagerWord": "Bacon", "spyWord": "Sausage" },
        { "villagerWord": "Egg", "spyWord": "Omelette" },
        { "villagerWord": "Waffle", "spyWord": "Pancake" },
        { "villagerWord": "Cookie", "spyWord": "Brownie" },
        { "villagerWord": "Cake", "spyWord": "Pie" },
        { "villagerWord": "Donut", "spyWord": "Muffin" },
        // Merged Fruits pairs
        { "villagerWord": "Apple", "spyWord": "Pear" },
        { "villagerWord": "Banana", "spyWord": "Plantain" },
        { "villagerWord": "Orange", "spyWord": "Grapefruit" },
        { "villagerWord": "Grapes", "spyWord": "Berries" },
        { "villagerWord": "Strawberry", "spyWord": "Raspberry" },
        { "villagerWord": "Watermelon", "spyWord": "Cantaloupe" },
        { "villagerWord": "Pineapple", "spyWord": "Mango" },
        { "villagerWord": "Lemon", "spyWord": "Lime" },
        { "villagerWord": "Peach", "spyWord": "Nectarine" },
        { "villagerWord": "Cherry", "spyWord": "Plum" },
        { "villagerWord": "Kiwi", "spyWord": "Fig" },
        { "villagerWord": "Blueberry", "spyWord": "Blackberry" },
        { "villagerWord": "Avocado", "spyWord": "Guacamole" },
        { "villagerWord": "Coconut", "spyWord": "Palm Tree" },
        { "villagerWord": "Pomegranate", "spyWord": "Cranberry" },
        { "villagerWord": "Apricot", "spyWord": "Persimmon" },
        { "villagerWord": "Papaya", "spyWord": "Passion Fruit" },
        { "villagerWord": "Lychee", "spyWord": "Rambutan" },
        { "villagerWord": "Tangerine", "spyWord": "Clementine" },
        { "villagerWord": "Durian", "spyWord": "Jackfruit" }
      ]
    },
    {
      "name": "Sports",
      "pairs": [
        { "villagerWord": "Soccer", "spyWord": "Football" },
        { "villagerWord": "Basketball", "spyWord": "Netball" },
        { "villagerWord": "Baseball", "spyWord": "Cricket" },
        { "villagerWord": "Tennis", "spyWord": "Badminton" },
        { "villagerWord": "Swimming", "spyWord": "Diving" },
        { "villagerWord": "Boxing", "spyWord": "MMA" },
        { "villagerWord": "Golf", "spyWord": "Mini-Golf" },
        { "villagerWord": "Skiing", "spyWord": "Snowboarding" },
        { "villagerWord": "Running", "spyWord": "Jogging" },
        { "villagerWord": "Cycling", "spyWord": "Motorbiking" },
        { "villagerWord": "Archery", "spyWord": "Darts" },
        { "villagerWord": "Fencing", "spyWord": "Kendo" },
        { "villagerWord": "Curling", "spyWord": "Bocce" },
        { "villagerWord": "Hockey", "spyWord": "Ice Hockey" },
        { "villagerWord": "Volleyball", "spyWord": "Beach Volleyball" },
        { "villagerWord": "Gymnastics", "spyWord": "Acrobatics" },
        { "villagerWord": "Surfing", "spyWord": "Wakeboarding" },
        { "villagerWord": "Karate", "spyWord": "Taekwondo" },
        { "villagerWord": "Sumo", "spyWord": "Wrestling" },
        { "villagerWord": "Sailing", "spyWord": "Canoeing" }
      ]
    },
    {
        "name": "City/Building",
        "pairs": [
            { "villagerWord": "House", "spyWord": "Mansion" },
            { "villagerWord": "School", "spyWord": "College" },
            { "villagerWord": "Hospital", "spyWord": "Clinic" },
            { "villagerWord": "Library", "spyWord": "Archive" },
            { "villagerWord": "Restaurant", "spyWord": "Diner" },
            { "villagerWord": "Airport", "spyWord": "Hangar" },
            { "villagerWord": "Museum", "spyWord": "Gallery" },
            { "villagerWord": "Bank", "spyWord": "Vault" },
            { "villagerWord": "Church", "spyWord": "Cathedral" },
            { "villagerWord": "Skyscraper", "spyWord": "High-rise" },
            { "villagerWord": "Bridge", "spyWord": "Tunnel" },
            { "villagerWord": "Stadium", "spyWord": "Arena" },
            { "villagerWord": "Mall", "spyWord": "Market" },
            { "villagerWord": "Hotel", "spyWord": "Motel" },
            { "villagerWord": "Police Station", "spyWord": "Jail" },
            { "villagerWord": "Fire Station", "spyWord": "Fire Hydrant" },
            { "villagerWord": "Post Office", "spyWord": "Mailbox" },
            { "villagerWord": "Factory", "spyWord": "Warehouse" },
            { "villagerWord": "Castle", "spyWord": "Palace" },
            { "villagerWord": "Lighthouse", "spyWord": "Beacon" }
        ]
    },
    {
      "name": "Animals/Plants/Nature",
      "pairs": [
        { "villagerWord": "Dog", "spyWord": "Wolf" },
        { "villagerWord": "Cat", "spyWord": "Lynx" },
        { "villagerWord": "Lion", "spyWord": "Tiger" },
        { "villagerWord": "Elephant", "spyWord": "Mammoth" },
        { "villagerWord": "Horse", "spyWord": "Donkey" },
        { "villagerWord": "Cow", "spyWord": "Bull" },
        { "villagerWord": "Chicken", "spyWord": "Rooster" },
        { "villagerWord": "Duck", "spyWord": "Goose" },
        { "villagerWord": "Shark", "spyWord": "Whale" },
        { "villagerWord": "Eagle", "spyWord": "Falcon" },
        { "villagerWord": "Snake", "spyWord": "Lizard" },
        { "villagerWord": "Frog", "spyWord": "Toad" },
        { "villagerWord": "Butterfly", "spyWord": "Moth" },
        { "villagerWord": "Bee", "spyWord": "Wasp" },
        { "villagerWord": "Spider", "spyWord": "Scorpion" },
        { "villagerWord": "Tree", "spyWord": "Bush" },
        { "villagerWord": "Flower", "spyWord": "Weed" },
        { "villagerWord": "Grass", "spyWord": "Lawn" },
        { "villagerWord": "Mountain", "spyWord": "Hill" },
        { "villagerWord": "River", "spyWord": "Stream" }
      ]
    },
    {
        "name": "Life",
        "pairs": [
            { "villagerWord": "Love", "spyWord": "Affection" },
            { "villagerWord": "Happiness", "spyWord": "Contentment" },
            { "villagerWord": "Sadness", "spyWord": "Melancholy" },
            { "villagerWord": "Anger", "spyWord": "Rage" },
            { "villagerWord": "Dream", "spyWord": "Fantasy" },
            { "villagerWord": "Work", "spyWord": "Job" },
            { "villagerWord": "Family", "spyWord": "Household" },
            { "villagerWord": "Marriage", "spyWord": "Union" },
            { "villagerWord": "Life", "spyWord": "Lifespan" },
            { "villagerWord": "Death", "spyWord": "Afterlife" },
            { "villagerWord": "Birth", "spyWord": "Childhood" },
            { "villagerWord": "Friend", "spyWord": "Acquaintance" },
            { "villagerWord": "Success", "spyWord": "Achievement" },
            { "villagerWord": "Failure", "spyWord": "Setback" },
            { "villagerWord": "Knowledge", "spyWord": "Wisdom" },
            { "villagerWord": "Fear", "spyWord": "Anxiety" },
            { "villagerWord": "Hope", "spyWord": "Wish" },
            { "villagerWord": "Time", "spyWord": "Eternity" },
            { "villagerWord": "Health", "spyWord": "Wellness" },
            { "villagerWord": "Money", "spyWord": "Wealth" }
        ]
    },
    {
      "name": "Character/Profession",
      "pairs": [
        { "villagerWord": "Doctor", "spyWord": "Surgeon" },
        { "villagerWord": "Teacher", "spyWord": "Tutor" },
        { "villagerWord": "Police Officer", "spyWord": "Sheriff" },
        { "villagerWord": "Firefighter", "spyWord": "Arsonist" },
        { "villagerWord": "Chef", "spyWord": "Baker" },
        { "villagerWord": "Artist", "spyWord": "Illustrator" },
        { "villagerWord": "Musician", "spyWord": "Composer" },
        { "villagerWord": "Writer", "spyWord": "Journalist" },
        { "villagerWord": "Engineer", "spyWord": "Mechanic" },
        { "villagerWord": "Pilot", "spyWord": "Captain" },
        { "villagerWord": "Lawyer", "spyWord": "Judge" },
        { "villagerWord": "Scientist", "spyWord": "Researcher" },
        { "villagerWord": "Farmer", "spyWord": "Gardener" },
        { "villagerWord": "Actor", "spyWord": "Stuntman" },
        { "villagerWord": "Dentist", "spyWord": "Orthodontist" },
        { "villagerWord": "Barber", "spyWord": "Hairdresser" },
        { "villagerWord": "Butcher", "spyWord": "Fishmonger" },
        { "villagerWord": "Plumber", "spyWord": "Electrician" },
        { "villagerWord": "Cashier", "spyWord": "Clerk" },
        { "villagerWord": "Soldier", "spyWord": "Marine" }
      ]
    },
    {
      "name": "Other",
      "pairs": [
        { "villagerWord": "Book", "spyWord": "Novel" },
        { "villagerWord": "Art", "spyWord": "Painting" },
        { "villagerWord": "History", "spyWord": "Past" },
        { "villagerWord": "Science", "spyWord": "Biology" },
        { "villagerWord": "Math", "spyWord": "Geometry" },
        { "villagerWord": "Language", "spyWord": "Grammar" },
        { "villagerWord": "War", "spyWord": "Conflict" },
        { "villagerWord": "Peace", "spyWord": "Harmony" },
        { "villagerWord": "King", "spyWord": "Monarch" },
        { "villagerWord": "Queen", "spyWord": "Ruler" },
        { "villagerWord": "Rich", "spyWord": "Affluent" },
        { "villagerWord": "Poor", "spyWord": "Impoverished" },
        { "villagerWord": "Hot", "spyWord": "Scorching" },
        { "villagerWord": "Cold", "spyWord": "Frigid" },
        { "villagerWord": "Big", "spyWord": "Huge" },
        { "villagerWord": "Small", "spyWord": "Microscopic" },
        { "villagerWord": "Happy", "spyWord": "Ecstatic" },
        { "villagerWord": "Sad", "spyWord": "Devastated" },
        { "villagerWord": "Magic", "spyWord": "Illusion" },
        { "villagerWord": "Miracle", "spyWord": "Wonder" }
      ]
    }
  ]
};